# Generated by Django 3.0 on 2020-01-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('binary', 'BINARY')], max_length=25)),
                ('id_cedula', models.BigIntegerField()),
                ('date_of_birth', models.DateField()),
                ('language', models.CharField(max_length=255)),
                ('id_harmond', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=255)),
                ('telephone_number', models.BigIntegerField()),
                ('marital_status', models.CharField(choices=[('single', 'SINGLE'), ('maried', 'MARIED')], max_length=25)),
                ('schedule', models.CharField(choices=[('morning', 'MORNING'), ('afternoon', 'AFTERNOON'), ('night', 'NIGHT')], max_length=25)),
                ('picture', models.ImageField(upload_to='')),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
    ]
